import { MigrationInterface, QueryRunner } from "typeorm";

export class InsertSampleTours1748735817504 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            INSERT INTO tours (name, description, price, duration, images, location, title, highlights, included, excluded, isActive, isNew, createdAt, updatedAt)
            VALUES 
            ('Tour Du Lịch Hạ Long', 
            'Khám phá vịnh Hạ Long - Di sản thiên nhiên thế giới với những hòn đảo đá vôi hùng vĩ và hang động kỳ bí.', 
            2500000, 
            2, 
            '["https://example.com/halong1.jpg", "https://example.com/halong2.jpg"]', 
            'Hạ Long, Quảng Ninh', 
            'Khám Phá Vịnh Hạ Long - Kỳ Quan Thiên Nhiên Thế Giới', 
            '["Thuyền kayak khám phá hang động", "Leo núi ngắm toàn cảnh vịnh", "Tắm biển tại bãi biển đẹp nhất"]', 
            '["Vé thuyền", "Ăn trưa", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            1, 
            GETDATE(), 
            GETDATE()),

            ('Tour Sapa Mùa Lúa Chín', 
            'Trải nghiệm vẻ đẹp của Sapa trong mùa lúa chín vàng, gặp gỡ người dân tộc thiểu số.', 
            3500000, 
            3, 
            '["https://example.com/sapa1.jpg", "https://example.com/sapa2.jpg"]', 
            'Sapa, Lào Cai', 
            'Sapa Mùa Lúa Chín - Thiên Đường Núi Rừng Tây Bắc', 
            '["Trekking qua ruộng bậc thang", "Thăm bản làng dân tộc", "Chợ phiên Sapa"]', 
            '["Vé cáp treo", "Ăn sáng, trưa, tối", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            1, 
            GETDATE(), 
            GETDATE()),

            ('Tour Phố Cổ Hội An', 
            'Khám phá di sản văn hóa thế giới Hội An với kiến trúc cổ kính và ẩm thực đặc sắc.', 
            1800000, 
            2, 
            '["https://example.com/hoian1.jpg", "https://example.com/hoian2.jpg"]', 
            'Hội An, Quảng Nam', 
            'Hội An - Phố Cổ Di Sản Văn Hóa Thế Giới', 
            '["Thăm phố cổ về đêm", "Làm gốm Thanh Hà", "Thưởng thức ẩm thực địa phương"]', 
            '["Vé tham quan", "Ăn trưa", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            0, 
            GETDATE(), 
            GETDATE()),

            ('Tour Đà Nẵng - Bãi Biển Đẹp', 
            'Tận hưởng kỳ nghỉ tại thành phố biển Đà Nẵng với những bãi biển đẹp nhất Việt Nam.', 
            2200000, 
            3, 
            '["https://example.com/danang1.jpg", "https://example.com/danang2.jpg"]', 
            'Đà Nẵng', 
            'Đà Nẵng - Thành Phố Đáng Sống Nhất Việt Nam', 
            '["Tắm biển Mỹ Khê", "Leo núi Ngũ Hành Sơn", "Thưởng thức hải sản"]', 
            '["Khách sạn 3 sao", "Ăn sáng", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            0, 
            GETDATE(), 
            GETDATE()),

            ('Tour Nha Trang - Đảo Hòn Tằm', 
            'Khám phá vẻ đẹp của Nha Trang và đảo Hòn Tằm với những bãi biển hoang sơ.', 
            2800000, 
            2, 
            '["https://example.com/nhatrang1.jpg", "https://example.com/nhatrang2.jpg"]', 
            'Nha Trang, Khánh Hòa', 
            'Nha Trang - Thiên Đường Biển Đảo', 
            '["Lặn ngắm san hô", "Tắm biển đảo Hòn Tằm", "Thưởng thức hải sản"]', 
            '["Vé tàu", "Ăn trưa", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            1, 
            GETDATE(), 
            GETDATE()),

            ('Tour Phú Quốc - Đảo Ngọc', 
            'Trải nghiệm kỳ nghỉ tại đảo ngọc Phú Quốc với những bãi biển đẹp nhất thế giới.', 
            4500000, 
            4, 
            '["https://example.com/phuquoc1.jpg", "https://example.com/phuquoc2.jpg"]', 
            'Phú Quốc, Kiên Giang', 
            'Phú Quốc - Thiên Đường Nghỉ Dưỡng', 
            '["Tắm biển Sao", "Thăm làng chài", "Thưởng thức hải sản"]', 
            '["Khách sạn 4 sao", "Ăn sáng", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            1, 
            GETDATE(), 
            GETDATE()),

            ('Tour Đà Lạt - Thành Phố Ngàn Thông', 
            'Khám phá thành phố ngàn thông Đà Lạt với khí hậu mát mẻ và cảnh quan thiên nhiên tuyệt đẹp.', 
            3200000, 
            3, 
            '["https://example.com/dalat1.jpg", "https://example.com/dalat2.jpg"]', 
            'Đà Lạt, Lâm Đồng', 
            'Đà Lạt - Thành Phố Mộng Mơ', 
            '["Thăm thác Datanla", "Vườn hoa thành phố", "Thưởng thức cà phê"]', 
            '["Khách sạn 3 sao", "Ăn sáng", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            0, 
            GETDATE(), 
            GETDATE()),

            ('Tour Mũi Né - Sa Mạc', 
            'Trải nghiệm sa mạc tại Mũi Né và khám phá những đồi cát đỏ độc đáo.', 
            1900000, 
            2, 
            '["https://example.com/muine1.jpg", "https://example.com/muine2.jpg"]', 
            'Mũi Né, Bình Thuận', 
            'Mũi Né - Sa Mạc Giữa Biển', 
            '["Leo đồi cát đỏ", "Tắm biển", "Thưởng thức hải sản"]', 
            '["Khách sạn 3 sao", "Ăn sáng", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            0, 
            GETDATE(), 
            GETDATE()),

            ('Tour Cần Thơ - Chợ Nổi', 
            'Khám phá văn hóa sông nước miền Tây tại Cần Thơ với chợ nổi Cái Răng nổi tiếng.', 
            2100000, 
            2, 
            '["https://example.com/cantho1.jpg", "https://example.com/cantho2.jpg"]', 
            'Cần Thơ', 
            'Cần Thơ - Tây Đô Sông Nước', 
            '["Thăm chợ nổi Cái Răng", "Vườn trái cây", "Thưởng thức ẩm thực miền Tây"]', 
            '["Khách sạn 3 sao", "Ăn sáng", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            0, 
            GETDATE(), 
            GETDATE()),

            ('Tour Sài Gòn - Thành Phố Không Ngủ', 
            'Khám phá Sài Gòn - thành phố sôi động nhất Việt Nam với văn hóa đa dạng.', 
            1500000, 
            2, 
            '["https://example.com/saigon1.jpg", "https://example.com/saigon2.jpg"]', 
            'TP.HCM', 
            'Sài Gòn - Thành Phố Không Ngủ', 
            '["Thăm Dinh Độc Lập", "Chợ Bến Thành", "Phố đi bộ Bùi Viện"]', 
            '["Khách sạn 3 sao", "Ăn sáng", "Hướng dẫn viên", "Bảo hiểm"]', 
            '["Chi phí cá nhân", "Đồ uống", "Quà lưu niệm"]', 
            1, 
            0, 
            GETDATE(), 
            GETDATE())
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM tours WHERE name IN (
            'Tour Du Lịch Hạ Long',
            'Tour Sapa Mùa Lúa Chín',
            'Tour Phố Cổ Hội An',
            'Tour Đà Nẵng - Bãi Biển Đẹp',
            'Tour Nha Trang - Đảo Hòn Tằm',
            'Tour Phú Quốc - Đảo Ngọc',
            'Tour Đà Lạt - Thành Phố Ngàn Thông',
            'Tour Mũi Né - Sa Mạc',
            'Tour Cần Thơ - Chợ Nổi',
            'Tour Sài Gòn - Thành Phố Không Ngủ'
        )`);
    }
} 